export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const GET_ALL_REVIEWS_REQUEST = 'GET_ALL_REVIEWS_REQUEST';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const GET_ALL_REVIEWS_FAILURE = 'GET_ALL_REVIEWS_FAILURE';

export const GET_REVIEW_SUMMARY_REQUEST = 'GET_REVIEW_SUMMARY_REQUEST';
export const GET_REVIEW_SUMMARY_SUCCESS = 'GET_REVIEW_SUMMARY_SUCCESS';
export const GET_REVIEW_SUMMARY_FAILURE = 'GET_REVIEW_SUMMARY_FAILURE';

export const GET_USER_REVIEW_REQUEST = 'GET_USER_REVIEW_REQUEST';
export const GET_USER_REVIEW_SUCCESS = 'GET_USER_REVIEW_SUCCESS';
export const GET_USER_REVIEW_FAILURE = 'GET_USER_REVIEW_FAILURE';

export const MARK_REVIEW_HELPFUL_REQUEST = 'MARK_REVIEW_HELPFUL_REQUEST';
export const MARK_REVIEW_HELPFUL_SUCCESS = 'MARK_REVIEW_HELPFUL_SUCCESS';
export const MARK_REVIEW_HELPFUL_FAILURE = 'MARK_REVIEW_HELPFUL_FAILURE';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';